apiVersion: v1
data:
  SLACK_WEBHOOK_URL: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAzMUU5NDVER1QvQjAzMVg1WUUyQkUvZlVzcmlTVTFjcUQ4SFlNSjJnaXNHUGhB
kind: Secret
metadata:
  creationTimestamp: null
  name: worker-secret
