apiVersion: batch/v1
kind: CronJob
metadata:
  name: worker-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: git-open-pull-request-monitor
            image: git-open-pull-request-monitor-slim-v1
            imagePullPolicy: Never
            env:
            - name: GIT_API_URL
              valueFrom:
                configMapKeyRef:
                  name: worker-config-map
                  key: GIT_API_URL
            - name: ALERT_THRESHOLD_DAYS 
              valueFrom:
                configMapKeyRef:
                  name: worker-config-map
                  key: ALERT_THRESHOLD_DAYS
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: worker-secret
                  key: SLACK_WEBHOOK_URL
            command: ["python"]
            args: ["./worker.py"]
          restartPolicy: OnFailure